"""
Unified output handling for file I/O operations.

Provides a single, consistent interface for saving summaries and content.
"""

from dataclasses import dataclass
from pathlib import Path

from precis.core.filename_utils import (
    get_model_suffix,
    get_name_from_source,
    sanitize_filename,
)

DEFAULT_OUTPUT_DIR = Path("outputs")


@dataclass
class ParsedPaperData:
    """Data container for saving parsed paper output."""

    name: str
    title: str
    source: str
    pages: int
    abstract: str
    sections_content: str


class OutputWriter:
    """
    Handles all file output operations.

    Centralizes file I/O to ensure consistent behavior across
    different content types (papers, notes, web pages).
    """

    def __init__(self, output_dir: Path | None = None) -> None:
        """
        Initialize the output writer.

        Args:
            output_dir: Directory for output files. Defaults to 'outputs/'.
        """
        self.output_dir = output_dir or DEFAULT_OUTPUT_DIR
        self._ensure_output_dir()

    def _ensure_output_dir(self) -> None:
        """Create output directory if it doesn't exist."""
        self.output_dir.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def get_model_suffix(provider: str | None, model: str | None) -> str:
        """
        Generate a filename suffix from provider and model.

        Delegates to the filename_utils module for consistency.

        Args:
            provider: LLM provider name (e.g., "claude", "openai").
            model: Model name (e.g., "claude-sonnet-4-5-20250929").

        Returns:
            Suffix string like "_claude_model" or empty string if no model.
        """
        if not provider or not model:
            return ""
        return get_model_suffix(provider, model)

    def save_summary(
        self,
        name: str,
        title: str,
        content: str,
        provider: str | None = None,
        model: str | None = None,
    ) -> Path:
        """
        Save a summary to a markdown file.

        Args:
            name: Base name for the file (without extension).
            title: Title to include in the file header.
            content: Summary content.
            provider: LLM provider name for filename suffix.
            model: Model name for filename suffix.

        Returns:
            Path to the saved file.
        """
        model_suffix = self.get_model_suffix(provider, model)
        filename = sanitize_filename(f"{name}{model_suffix}_summary")
        path = self.output_dir / f"{filename}.md"

        with open(path, "w", encoding="utf-8") as f:
            f.write(f"# {title}\n\n")
            if provider and model:
                f.write(f"*Generated by: {provider}/{model}*\n\n")
            f.write(content)

        print(f"✅ Summary saved to: {path}")
        return path

    def save_content(self, name: str, content: str, header: str = "") -> Path:
        """
        Save raw content to a text file.

        Args:
            name: Base name for the file (without extension).
            content: Content to save.
            header: Optional header to prepend.

        Returns:
            Path to the saved file.
        """
        filename = sanitize_filename(f"{name}_content")
        path = self.output_dir / f"{filename}.txt"

        with open(path, "w", encoding="utf-8") as f:
            if header:
                f.write(header)
                f.write("=" * 80 + "\n\n")
            f.write(content)

        print(f"✅ Content saved to: {path}")
        return path

    def save_parsed_paper(self, paper_data: ParsedPaperData) -> Path:
        """
        Save a parsed paper to a text file.

        Args:
            paper_data: ParsedPaperData containing all paper information.

        Returns:
            Path to the saved file.
        """
        filename = sanitize_filename(f"{paper_data.name}_parsed")
        path = self.output_dir / f"{filename}.txt"

        with open(path, "w", encoding="utf-8") as f:
            f.write("=" * 80 + "\n")
            f.write(f"TITLE: {paper_data.title}\n")
            f.write(f"SOURCE: {paper_data.source}\n")
            f.write(f"PAGES: {paper_data.pages}\n")
            f.write("=" * 80 + "\n\n")

            if paper_data.abstract:
                f.write("ABSTRACT\n")
                f.write("-" * 40 + "\n")
                f.write(paper_data.abstract + "\n\n")

            f.write(paper_data.sections_content)

        print(f"✅ Parsed content saved to: {path}")
        return path

    @staticmethod
    def get_name_from_source(path_or_url: str) -> str:
        """
        Extract a suitable filename from a path or URL.

        Delegates to filename_utils module for consistency.

        Args:
            path_or_url: Local path or URL.

        Returns:
            Sanitized name suitable for use in filenames.
        """
        return get_name_from_source(path_or_url)
