"""Characterization tests for OutputWriter file I/O."""

from pathlib import Path

from precis.core.output import OutputWriter, ParsedPaperData


def test_save_summary_writes_markdown_with_metadata(tmp_path: Path) -> None:
    writer = OutputWriter(output_dir=tmp_path)
    path = writer.save_summary(
        name="my paper",
        title="My Paper",
        content="The summary body.",
        provider="claude",
        model="claude-sonnet-4-5",
    )

    assert path == tmp_path / "my_paper_claude_claude-sonnet-4-5_summary.md"
    text = path.read_text(encoding="utf-8")
    assert text.startswith("# My Paper\n\n")
    assert "*Generated by: claude/claude-sonnet-4-5*" in text
    assert "The summary body." in text


def test_save_summary_without_model_omits_suffix(tmp_path: Path) -> None:
    writer = OutputWriter(output_dir=tmp_path)
    path = writer.save_summary(name="note", title="Note", content="x")
    assert path == tmp_path / "note_summary.md"


def test_save_content_writes_header_and_body(tmp_path: Path) -> None:
    writer = OutputWriter(output_dir=tmp_path)
    path = writer.save_content("page", "body text", header="URL: http://x\n")

    assert path == tmp_path / "page_content.txt"
    text = path.read_text(encoding="utf-8")
    assert text.startswith("URL: http://x\n")
    assert "body text" in text


def test_save_parsed_paper(tmp_path: Path) -> None:
    writer = OutputWriter(output_dir=tmp_path)
    data = ParsedPaperData(
        name="paper",
        title="Title",
        source="/src.pdf",
        pages=5,
        abstract="The abstract.",
        sections_content="SECTION BODY",
    )
    path = writer.save_parsed_paper(data)

    assert path == tmp_path / "paper_parsed.txt"
    text = path.read_text(encoding="utf-8")
    assert "TITLE: Title" in text
    assert "PAGES: 5" in text
    assert "The abstract." in text
    assert "SECTION BODY" in text


def test_output_dir_is_created(tmp_path: Path) -> None:
    target = tmp_path / "nested" / "outputs"
    OutputWriter(output_dir=target)
    assert target.is_dir()
